### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/MDAnalysis.github.io#129]
As MDAnalysis uses Google Analytics, [we need to have a privacy policy and notify users about it (#7 on the terms and conditions)](https://marketingplatform.google.com/about/analytics/terms/us/).

[Here's a template policy](https://termly.io/resources/templates/privacy-policy-template/) we could borrow.

**Comment by kain88-de** [comment]
Why do we use google analytics by the way?

**Comment by orbeckst** [comment]
Since the beginning we had analytics on all our sites. In principle the idea was to learn how users use the site. In practice we haven't made a lot of use of it. But for instance, it will be interesting to see if people start shifting to the User Guide instead of docs. @lilyminium observed that people typically filter through the getting started pages on the website and then end up in the UG.

Looking at webpage visitors is one of the few ways in which we can measure interest. Others are paper citations, downloads, subscribers on the lists, number of developers, number of contributors. All of these measures are imperfect. However, when having to demonstrate (e.g., for grant applications) that this project has impact then you really want to have as many ways as possible to provide a multi-faceted view.

**Comment by orbeckst** [comment]
Maybe NumFOCUS has some advice?

**Comment by orbeckst** [comment]
Reading through the [termly privacy policy](https://termly.io/our-privacy-policy/) as an example, it might be useful to have a bunch of contact addresses such as "privacy@mdanalysis.org" or "info@mdanalysis.org". Or at least have a mailinglist that allows public posting and that is read by core devs (similar to mdnalysis-conduct@googlegroups.com).

**Comment by orbeckst** [comment]
Example policy generated by termly – I might not have clicked all the right things. I struck out a few things that we probably don't need. I added a section that includes Google Analytics, GitHub pages, Cloudflare and Algolia Search (modelled after [termly's policy](https://termly.io/our-privacy-policy/) _4. WHO WILL YOUR INFORMATION BE SHARED WITH?_

I left in termly's "request form to remove data" at the end. Not sure if we want to keep this. Ultimately we don't keep any data; only 3rd party providers.

# PRIVACY NOTICE

Last updated June 12, 2020


Thank you for choosing to be part of our community at MDAnalysis (“Company”, “we”, “us”, or “our”). We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about our notice, or our practices with regards to your personal information, please contact us at mdnalysis-devel@googlegroups.com.

When you visit our website https://www.mdanalysis.org, and use our services, you trust us with your personal information. We take your privacy very seriously. In this privacy notice, we seek to explain to you in the clearest way possible what information we collect, how we use it and what rights you have in relation to it. We hope you take some time to read through it carefully, as it is important. If there are any terms in this privacy notice that you do not agree with, please discontinue use of our Sites and our services.

This privacy notice applies to all information collected through our website (such as https://www.mdanalysis.org), and/or any related services, sales, marketing or events (we refer to them collectively in this privacy notice as the "Services").

Please read this privacy notice carefully as it will help you make informed decisions about sharing your personal information with us.


## TABLE OF CONTENTS

1. WHAT INFORMATION DO WE COLLECT?
2. HOW DO WE USE YOUR INFORMATION?
3. WILL YOUR INFORMATION BE SHARED WITH ANYONE?
4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?
5. HOW LONG DO WE KEEP YOUR INFORMATION?
6. DO WE COLLECT INFORMATION FROM MINORS?
7. WHAT ARE YOUR PRIVACY RIGHTS?
8. CONTROLS FOR DO-NOT-TRACK FEATURES
9. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?
10. DO WE MAKE UPDATES TO THIS POLICY?
11. HOW CAN YOU CONTACT US ABOUT THIS POLICY?


## 1. WHAT INFORMATION DO WE COLLECT?


### Information automatically collected

In Short:   _Some information — such as IP address and/or browser and device characteristics — is collected automatically when you visit our Services._

We automatically collect certain information when you visit, use or navigate the Services. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Services and other technical information. This information is primarily needed to maintain the security and operation of our Services, and for our internal analytics and reporting purposes.

Like many businesses, we also collect information through cookies and similar technologies.


## 2. HOW DO WE USE YOUR INFORMATION?

In Short:  _We process your information for purposes based on legitimate business interests, the fulfillment of our contract with you, compliance with our legal obligations, and/or your consent._

We use personal information collected via our Services for a variety of business purposes described below. We process your personal information for these purposes in reliance on our legitimate business interests, in order to enter into or perform a contract with you, with your consent, and/or for compliance with our legal obligations. We indicate the specific processing grounds we rely on next to each purpose listed below.

We use the information we collect or receive:

*For other Business Purposes.* We may use your information for other Business Purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Services, products, marketing and your experience. We may use and store this information in aggregated and anonymized form so that it is not associated with individual end users and does not include personal information. We will not use identifiable personal information without your consent.


## 3. WILL YOUR INFORMATION BE SHARED WITH ANYONE?

In Short:  _We only share information with your consent, to comply with laws, to provide you with services, to protect your rights, or to fulfill business obligations._

We may process or share data based on the following legal basis:

-   *Consent*: We may process your data if you have given us specific consent to use your personal information in a specific purpose.
-    *Legitimate Interests*: We may process your data when it is reasonably necessary to achieve our legitimate business interests.
-    ~*Performance of a Contract*: Where we have entered into a contract with you, we may process your personal information to fulfill the terms of our contract.~
-    *Legal Obligations*: We may disclose your information where we are legally required to do so in order to comply with applicable law, governmental requests, a judicial proceeding, court order, or legal process, such as in response to a court order or a subpoena (including in response to public authorities to meet national security or law enforcement requirements).
-    *Vital Interests*: We may disclose your information where we believe it is necessary to investigate, prevent, or take action regarding potential violations of our policies, suspected fraud, situations involving potential threats to the safety of any person and illegal activities, or as evidence in litigation in which we are involved.

More specifically, we may need to process your data or share your personal information in the following situations:

-    *Vendors, Consultants and Other Third-Party Service Providers.* We may share your data with third party vendors, service providers, contractors or agents who perform services for us or on our behalf and require access to such information to do that work. Examples include: payment processing, data analysis, email delivery, hosting services, customer service and marketing efforts. We may allow selected third parties to use tracking technology on the Services, which will enable them to collect data about how you interact with the Services over time. This information may be used to, among other things, analyze and track data, determine the popularity of certain content and better understand online activity. Unless described in this Policy, we do not share, sell, rent or trade any of your information with third parties for their promotional purposes.

-    *Business Transfers.* We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.

-    ~*Third-Party Advertisers.* We may use third-party advertising companies to serve ads when you visit the Services. These companies may use information about your visits to our Website(s) and other websites that are contained in web cookies and other tracking technologies in order to provide advertisements about goods and services of interest to you.~

-    ~*Affiliates.* We may share your information with our affiliates, in which case we will require those affiliates to honor this privacy notice. Affiliates include our parent company and any subsidiaries, joint venture partners or other companies that we control or that are under common control with us.~

### Who will your information be shared with?

In short: _We only share information with the following third parties._

- *Cloud computing services*: Cloudflare https://www.cloudflare.com/. Requests are routed through Cloudflare's caches  and DNS resolvers; please see https://www.cloudflare.com/privacypolicy/ for how Cloudflare collects information. 
- *Search*: algolia https://www.algolia.com/ provides search functionality. Your search terms are transmitted to algolia to provide the search functionality on our site. Please see https://www.algolia.com/policies/privacy/ (_9. Subscriber Data submitted to our Services or collected through our Services (on behalf of our subscribers_) to learn how algolia uses your data. 
- *Web and Mobile Analytics*: Google Analytics. To see how Google uses data collected from visiting our site please see https://www.google.com/policies/privacy/partners/
- *Website hosting*: GitHub https://github.com/ hosts the web pages as GitHub Pages; please see GitHub's privacy policy https://help.github.com/en/github/site-policy/github-privacy-statement#additional-services regarding accessing GitHub Pages.

## 4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?

In Short:  _We may use cookies and other tracking technologies to collect and store your information._

We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Policy.


## 5. HOW LONG DO WE KEEP YOUR INFORMATION?

In Short:  _We keep your information for as long as necessary to fulfill the purposes outlined in this privacy notice unless otherwise required by law._

We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting or other legal requirements). No purpose in this policy will require us keeping your personal information for longer than 90 days.

When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize it, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.


## 6. DO WE COLLECT INFORMATION FROM MINORS?

In Short:  _We do not knowingly collect data from or market to children under 18 years of age._

We do not knowingly solicit data from or market to children under 18 years of age. By using the Services, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the Services. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we have collected from children under age 18, please contact us at mdnalysis-devel@googlegroups.com.


## 7. WHAT ARE YOUR PRIVACY RIGHTS?

In Short:  _You may review, change, or terminate your account at any time._

If you are resident in the European Economic Area and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here: http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm.

*Cookies and similar technologies:* Most Web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove cookies and to reject cookies. If you choose to remove cookies or reject cookies, this could affect certain features or services of our Services. To opt-out of interest-based advertising by advertisers on our Services visit http://www.aboutads.info/choices/.


## 8. CONTROLS FOR DO-NOT-TRACK FEATURES

Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (“DNT”) feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. No uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice.


## 9. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?

In Short:  _Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information._

California Civil Code Section 1798.83, also known as the “Shine The Light” law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.

If you are under 18 years of age, reside in California, and have a registered account with the Services, you have the right to request removal of unwanted data that you publicly post on the Services. To request removal of such data, please contact us using the contact information provided below, and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Services, but please be aware that the data may not be completely or comprehensively removed from our systems.


## 10. DO WE MAKE UPDATES TO THIS POLICY?

In Short:  _Yes, we will update this policy as necessary to stay compliant with relevant laws._

We may update this privacy notice from time to time. The updated version will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice frequently to be informed of how we are protecting your information.


## 11. HOW CAN YOU CONTACT US ABOUT THIS POLICY?

If you have questions or comments about this policy, you may email us at mdnalysis-devel@googlegroups.com or by post to:
MDAnalysis 
__________
__________


## HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?

Based on the laws of some countries, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please submit a request form by clicking [here](https://app.termly.io/notify/5529ede9-8433-4fd1-a402-ef4a9b918298). We will respond to your request within 30 days.

This privacy policy was created using [Termly’s Privacy Policy Generator](https://termly.io/products/privacy-policy-generator/?ftseo).

**Comment by orbeckst** [comment]
termly also suggests a Cookie policy and an opt-in banner for cookies, i.e., a [cookie consent manager](https://help.termly.io/support/solutions/articles/60000666986-getting-started-on-your-implementation). In order to initially block cookies until visitors consent, one has to disable cookie collection as described here:  https://help.termly.io/support/solutions/articles/60000666989-how-to-block-third-party-cookies

**Comment by orbeckst** [comment]
More reading: https://termly.io/resources/articles/google-analytics-privacy-policy/

**Comment by kain88-de** [comment]
What about an alternative to google analytics?

Like https://www.goatcounter.com/

**Comment by orbeckst** [comment]
I am open to it. 

No GDPR necessary sounds like a good thing.  I assume it will still give us basic usage stats. 

Does anyone think we need the fine grained data from Google Analytics? Perhaps “collecting just because we can and because Google makes it easy” is not the best approach to privacy….

**Comment by richardjgowers** [comment]
Yeah I’d sooner turn it off / use something self contained than Google.

**Comment by kain88-de** [comment]
So I read a bit more. Even with goatcounter we would need a GDPR notice. But no cookie consent banner (yeah). As long as we want to have some type of analytics we will need a privacy notice. A different software alternative to google analytics is unfortunately a different discussion. 

About the privacy notice. I do like the termy template. I'm not sure about the delete data statement. As MDAnalysis we do not have any data personally. Everything goes to third parties. Where we have no means to access the data in any way. Can we make such a statement? 

This deletion right is another problem. With a tool like goatcounter that is impossible, even self-hosted. Because of the deanonymization algorithm, we cannot know which data belongs to a person. I do know some legal arguments that this is enough, but I'm not a lawyer.

**Comment by orbeckst** [comment]
I would go with the fact that we do not collect any data in our own services. We do not collect any personally identifiable information. We do not manage any accounts (there are some sections that refer to accounts that we should remove/alter). 

Maybe NumFOCUS has some suggestions, they offered to have a look. 

Either way, we can start removing Google Analytics from the site (and possibly also from the docs... the js might be embedded there, too—need to check).

**Comment by orbeckst** [comment]
According to NumFOCUS, their Privacy Policy is binding for all projects, which includes us. They are currently updating theirs. We have two options
1. Link to NF and also list our 3rd party applications and data use
2. Have our own policy but making sure that nothing in our policy contradicts the NF one.

**Comment by kain88-de** [comment]
Option 1 sounds good to me.

**Comment by orbeckst** [comment]
Goatcounter claims that their use does not need a GDPR https://www.goatcounter.com/gdpr.

In any case, if PR #131 is merged then we need to replace the note on GA with a note on Goatcounter.

**Comment by orbeckst** [comment]
NF‘s Privacy Policy https://numfocus.org/privacy-policy

**Comment by orbeckst** [comment]
Goatcounter is now active (PR #132, issue #131) and stats are available at https://mdanalysis.goatcounter.com/.

I changed the settings
- stats are visible _without login_ (should we not have publicly visible stats?)
- data are deleted after 90 days (used to be kept infinitely)

Are these settings ok or should they be changed? This information should go into our Privacy Policy.

**Comment by lilyminium** [comment]
Visible stats would help transparency in terms of the data collected, and I can't see much sensitive info there (although I suppose right now I can guess someone in the US visits the site on a large iPhone ;-). Would keeping the data be beneficial for things like grant applications (e.g. X monthly visitors in 2020)?

**Comment by orbeckst** [comment]
> US visits the site on a large iPhone ;-)

That wasn't me then... I looked at it from an iPad :-p

> Would keeping the data be beneficial for things like grant applications (e.g. X monthly  visits in 2020)?

Sure, we  can bump it up to 365 days to get yearly stats; might be useful. I generally like the idea of having such data automatically disappear, though.

**Comment by orbeckst** [comment]
I changed the data retention interval to 365 days.

>>   Would keeping the data be beneficial for things like grant applications (e.g. X monthly visits in 2020)?
>
> Sure, we can bump it up to 365 days to get yearly stats; might be useful. I generally like the idea of having such data automatically disappear, though.

**Comment by kain88-de** [comment]
The stat counter is really nice. Interesting to see what people actually look at.
