### ISSUE TITLE
https://docs.mdanalysis.org/ points to UserGuide, not the docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#136]
https://docs.mdanalysis.org redirects me to https://docs.mdanalysis.org/1.0.0/ which is the User Guide.

Instead it should redirect to the 1.0.0 package docs (i.e., https://www.mdanalysis.org/docs/).

https://docs.mdanalysis.org/2.0.0-dev0/ is correct.

**Comment by lilyminium** [comment]
😞

**Comment by lilyminium** [comment]
@orbeckst I can either make a PR to update `.travis.yml` on mdanalysis/master, manually build 1.0.0 docs and push to gh-pages, or just remove that folder so it redirects to 2.0.0-dev instead

**Comment by orbeckst** [comment]
No idea what the best option is – if changing master’s .travis.yml will fix the issue then maybe do that as it leaves a clear record? But honestly, you know better than I what to do ;-)

**Comment by lilyminium** [comment]
Sorry, I should have posted what I did as a new comment instead of editing the other one! I pushed 1.0 docs to gh-pages (fixing this issue), and opened a new PR to mdanalysis/mdanalysis so we can also build docs when pull requests are merged into master / whichever branches that Travis can run tests on. (so, options 1 and 2)

If that gets backported to 1.0.1 then docs will get built for that branch too which might be handy (e.g. updating bug fixes, typos, and installation instructions; and triggering doc rebuilds in case they’re needed in the future). I left this open as a reminder to see that through but will close as the actual issue is fixed <https://docs.mdanalysis.org/1.0.0/>.
