### ISSUE TITLE
Examples gallery

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/MDAnalysis.github.io#4]
A good addition to the homepage would be a list of examples, probably best presented as ipython notebooks.  These could be hosted on this site, or could be links to other sites.  This would probably sit under the basic example and tutorial links on the left hand side.

**Comment by orbeckst** [comment]
Good idea. Please add suggestions.

* [PSAnalysis Tutorial](https://github.com/Becksteinlab/PSAnalysisTutorial)
* [Flows](http://sbcb.bioch.ox.ac.uk/flows/) (streamline visualization)

**Comment by orbeckst** [comment]
[papers citing MDAnalysis](https://scholar.google.com/scholar?cites=14957293613081676111&as_sdt=805&sciodt=0,3&hl=en) from Google Scholar.

**Comment by orbeckst** [comment]
See also mailing list threads on the
* [users list](https://groups.google.com/d/msg/mdnalysis-discussion/6jgArIgdva0/qzKHgFthBQAJ)
* [developers list](https://groups.google.com/d/msg/mdnalysis-devel/6jgArIgdva0/beZ3-XbOCwAJ)

**Comment by richardjgowers** [comment]
I'm going to try and put together a short notebook for all the polymer tools:

https://github.com/richardjgowers/persistence_length_tutorial/blob/master/tutorial.ipynb

**Comment by richardjgowers** [comment]
So it looks like the math in my notebook doesn't work, and github doesn't like rendering long notebooks either, so it might be smarter to convert them to markdown

**Comment by orbeckst** [comment]
Link through nbviewer?

--
Oliver Beckstein
email: orbeckst@gmail.com
skype: orbeckst


Am Oct 1, 2015 um 14:32 schrieb Richard Gowers <notifications@github.com>:

**Comment by orbeckst** [comment]
http://nbviewer.ipython.org/github/richardjgowers/persistence_length_tutorial/blob/master/tutorial.ipynb looks fine.

**Comment by richardjgowers** [comment]
Yeah I think repo hosted on github and rendered with nbviewer looks like the best solution

**Comment by philipwfowler** [comment]
Maybe a more visual way would be to link to posters in e.g. FigShare (and then encourage posters to put in FigShare)?

**Comment by orbeckst** [comment]
I can't see why not both!

**Comment by philipwfowler** [comment]
I've had a couple of papers where MDAnalysis has been vital. 

1. Jefferys E, Sansom MSP, Fowler PW^ Visualising large three-component lipid bilayers that phase separate and undulate. (2014) RSC Faraday Discussion 169 209-223 http://dx.doi.org/10.1039/c3fd00131h

Here it is the "gateway drug" since it enables me to use scikit-image on simulations of phase-separating lipid bilayers. Example code here
https://github.com/philipwfowler/fd169-image-processing-example.git

2, Fowler PW, Orwick-Rydmark M, Radestock S, Solcan N, Dijkman P, Lyons JA, Kwok J, Caffrey M, Watts A, Forrest LR and Newstead S. Gating topology of the proton coupled oligopeptide symporters. (2015) Structure 23 290-301 (doi:10.1016/j.str.2014.12.012)[http://dx.doi.org/10.1016/j.str.2014.12.012]

Here I wrote a (very simple) MDAnalysis script to map a (published) rotamer library of MTSSL spin labels onto two positions in this membrane transporter so we could try and compare directly to DEER data. The rotamer library is the same one as used in the MMM package that experimentalists use, but crucially allowed me to apply it to a whole trajectory rather than one PDB at a time...

The paper was featured on the cover:
http://www.cell.com/structure/issue?pii=S0969-2126%2814%29X0014-6

And the code (made much more professional by Oli) ended up in the MDAnalysis 
https://github.com/MDAnalysis/RotamerConvolveMD

**Comment by richardjgowers** [comment]
Awesome thanks, I think I'm putting this together in Nov, so it looks like we can have an entire weird and wonderful Lipid analysis section

**Comment by orbeckst** [comment]
Examples of using HOLE:
* [HOLE module](https://gist.github.com/orbeckst/64c0bd5a037b3e434cc8ee6732030252)
* [Using HOLE in MDAnalysis with order parameters](https://gist.github.com/orbeckst/a0c856f58059112538591af108df6d59)

**Comment by orbeckst** [comment]
See also MDAnalysis/MDAnalysisCookbook#3 : how about starting with a cookbook notebook folder?

**Comment by orbeckst** [comment]
Example for calculating and displaying RMSF
* SciPy paper
* [Simple RMSF b-factor coloring with MDAnalysis](http://nbviewer.jupyter.org/gist/orbeckst/6bea4a4be3ad0eb541e105edd58e93bf)

**Comment by orbeckst** [comment]
With the new binder repository https://github.com/MDAnalysis/binder-notebook we can publish all these suggestions there *and* make them immediately runnable.

I will leave this issue open for right now.
